language: rust

rust:
  - stable
  - beta

matrix:
  include:
  - rust: nightly
    env: FEATURE="--features dev"

script:
  - cargo test $FEATURE 2>&1 | awk 'BEGIN {flag = 0} {print} /warning/ {flag = 1}  END{if (flag>0) {print "Please fix warnings"; exit 1}}'
