language: rust

rust:
  - stable
  - beta

env:
  - RUSTFLAGS=-Dwarnings

matrix:
  include:
  - rust: nightly
    env:
      - FEATURE="--features dev"
      - RUSTFLAGS=-Dwarnings

script:
  - cargo test $FEATURE
