language: rust
sudo: false

os:
 - linux
 - osx

addons:
  apt:
    packages:
      - gcc-multilib

env:
  global:
    - RUSTFLAGS=--deny=warnings
    - FEATURES="push process"
    - ARCH=i686

# Must be present for matrix.
rust:

matrix:
  fast_finish: true
  include:
  - rust: nightly
  - rust: beta
  - rust: stable
    install:
      - rustup component add clippy-preview
      - rustup component add rustfmt-preview
    before_script:
      - cargo fmt --all -- --check
      - cargo clippy --all -- -D clippy
  allow_failures:
  - rust: nightly

script:
  - cargo test --features="$FEATURES"
  - |
    if [ $TRAVIS_RUST_VERSION = 'stable' ]; then
        # Clean up.
        cargo clean;
        # Test 32-bit versions. rust-prometheus only supports stable rust on 32-bit platforms.
        curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash;
    fi
