language: rust

rust:
  - stable
  - beta

matrix:
  include:
  - rust: nightly
    env: FEATURE="--features dev"

script:
  - cargo test $FEATURE | grep warning | awk '{print} END{if(NR>0) {exit 1}}'
