language: rust

os:
 - linux
 - osx

rust:
  - stable
  - beta

env:
  - RUSTFLAGS=-Dwarnings

script:
  - cargo test

matrix:
  include:
  - rust: nightly
    script:
      - cargo test --features="dev nightly process"
