[package]
name = "prometheus"
version = "0.2.8"
keywords = ["prometheus", "metrics"]
authors = ["overvenus@gmail.com", "siddontang@gmail.com"]

description = "a rust Prometheus client"
repository = "https://github.com/pingcap/rust-prometheus"
license = "Apache-2.0"

include = [
    "src/*.rs",
    "Cargo.toml",
]

[features]
default = []
dev = ["clippy"]
nightly = []
push = ["hyper", "libc"]
process = ["libc", "procinfo"]

[[bench]]
name = "benches"

[dependencies]
protobuf = "1.0"
quick-error = "0.2"
clippy = {version = "^0", optional = true}
fnv = "1.0.3"
lazy_static = "0.2.1"
libc = {version = "0.2", optional = true}
cfg-if = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = {version = "0.3", optional = true}

[dependencies.hyper]
version = "0.9"
# disable hyper ssl
#  refer to https://github.com/hyperium/hyper/issues/903#issuecomment-242798266
default-features = false
optional = true

[dev-dependencies]
getopts = "0.2.14"
hyper = {version = "0.9", default-features = false}
