[package]
name = "prom"
version = "0.1.0"
keywords = ["prometheus", "metrics"]

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "example_hyper"
path = "example/example_hyper.rs"

[[bin]]
name = "example_embed"
path = "example/example_embed.rs"

[dependencies]
protobuf = "1.0"
quick-error = "0.2"
clippy = {version = "*", optional = true}
fnv = "1.0.3"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
