[package]
name = "prometheus"
version = "0.2.5"
keywords = ["prometheus", "metrics"]
authors = ["overvenus@gmail.com", "siddontang@gmail.com"]

description = "a rust Prometheus client"
repository = "https://github.com/pingcap/rust-prometheus"
license = "Apache-2.0"

include = [
    "src/*.rs",
    "Cargo.toml",
]

[features]
default = []
dev = ["clippy"]

[[bench]]
name = "benches"

[dependencies]
protobuf = "1.0"
quick-error = "0.2"
clippy = {version = "^0", optional = true}
fnv = "1.0.3"
lazy_static = "0.2.1"

[dev-dependencies.hyper]
version = "0.9"
