[package]
name = "prometheus"
version = "0.3.3"
license = "Apache-2.0"
keywords = ["prometheus", "metrics"]
authors = ["overvenus@gmail.com", "siddontang@gmail.com"]
description = "Prometheus instrumentation library for Rust applications."
readme = "README.md"
repository = "https://github.com/pingcap/rust-prometheus"
homepage = "https://github.com/pingcap/rust-prometheus"
documentation = "https://docs.rs/prometheus"

include = [
    "LICENSE",
    "Cargo.toml",
    "src/**/*.rs",
    "proto/**/*.rs",
    "benches/**/*.rs",
]

[badges]
travis-ci = { repository = "pingcap/rust-prometheus" }

[features]
default = []
dev = ["clippy"]
nightly = ["libc", "spin/unstable"]
push = ["hyper", "libc"]
process = ["libc", "procinfo"]

[[bench]]
name = "benches"
path = "benches/benches.rs"

[dependencies]
protobuf = "1.4"
quick-error = "0.2"
clippy = {version = "^0", optional = true}
fnv = "1.0"
lazy_static = "0.2"
libc = {version = "0.2", optional = true}
cfg-if = "0.1"
spin = {version = "0.4", default-features = false}

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = {version = "0.3", optional = true}

[dependencies.hyper]
version = "0.9"
# disable hyper ssl
#  refer to https://github.com/hyperium/hyper/issues/903#issuecomment-242798266
default-features = false
optional = true

[dev-dependencies]
getopts = "0.2"
hyper = {version = "0.9", default-features = false}
